services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"

  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=hml
    env_file:
      - .env.hml

