version: "3.8"
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    ports:
      - "5433:5432"
  app:
    build: .
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=app
      - PGPORT=5432
